### ISSUE TITLE
No response on dbus calls after many Associations added or removed

### ISSUE THREAD

**Issue by randomnezz** [openbmc/phosphor-objmgr#23]
When many objects with `xyz.openbmc_project.Association.Definitions` interface are added or removed in dbus tree observed behavior is that the service is not responding to any dbus requests - timeout on dbus. Example command GetSubTree:
> busctl call xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper GetSubTree sias "/xyz/openbmc_project/inventory" 0 0

Side effect observed is also that process mapperx uses lots of resources (circa 50% cpu on my setup) indicating it is busy and that's why it doesn't respond.

The mapper should respond to queries with some status indicating it is busy or with correct response, i.e. response according to the state when the request is received.

Can be reproduced with [dbus sensor tester](https://github.com/openbmc/openbmc-tools/tree/master/dbus_sensor_tester) with patch adding Associations interface
[0001-add-associations.zip](https://github.com/openbmc/phosphor-objmgr/files/9239904/0001-add-associations.zip)
On my setup noticeable timeout happens with 2000 objects added.

**Comment by bradbishop** [comment]
hi @randomnezz, thanks for the bug report.  I can't say I disagree with anything you've said.  Do you have any thoughts on ways to improve the situation?

> or with correct response

Can you elaborate on this?  Are you getting incorrect responses or are requests timing out or both?

**Comment by mdmillerii** [comment]
Note 50% of a 2 cpu system like an ast2600 is one core 100%.

**Comment by randomnezz** [comment]
> hi @randomnezz, thanks for the bug report. I can't say I disagree with anything you've said. Do you have any thoughts on ways to improve the situation?
> 
> > or with correct response
> 
> Can you elaborate on this? Are you getting incorrect responses or are requests timing out or both?

Requests are timing out. I think proper solution would be that processing incoming requests should have higher priority. That means if request is received while the mapper is still processing some recent object changed (adding/removing associations etc.) it should respond correctly with information that has been processed up to the point when request was received. If that is not feasible/good then it should respond with some status indicating it is busy.

**Comment by amboar** [comment]
Last time I saw this kind of issue with the mapper it was busy spinning in userspace doing something inefficient. As such I suspect it isn't a matter of poor prioritisation but rather data structures that fail to scale, and we need to profile and eliminate those inefficiencies. @geissonator do have the data handy from when we were tracking this internally?

**Comment by geissonator** [comment]
> @geissonator do have the data handy from when we were tracking this internally?

No, our most recent issues have been solved via making the software using d-bus/mapper more efficient. For example our fan control code was running a 1 second polling loop, and it was re-querying mapper for every thermal sensor in the system on every loop. We changed the fan code to cache the mapper response.

It sounds to me like the test here is going to cause a problem by overloading the system, the question is what the mappers behavior should be when this occurs.

**Comment by spinler** [comment]
I tried that dbus sensor tester, and the mapper ignored it because it doesn't claim a real busname.  After I fixed that, I could see the mapper happily creating 4000 InterfacesAdded signals, one for each side of the new association. That of course takes CPU, and it did delay responses by several seconds, but on AST2600 hardware it didn't hit the 25s default D-bus timeout so nothing fails.

I can't claim I would know how to make that better... coroutines?  Patches accepted.

**Comment by amboar** [comment]
IMO the best bet is to trace it out with `perf` and flamegraphs and see what we need to fix. Is that info you could attach here on the bug @randomnezz?

**Comment by randomnezz** [comment]
@amboar I'm having trouble getting user space stack traces (I don't have experience with perf). I am attaching what I got for now, but it might not be reliable.. seems like most of the time is spent on memory management though.
![flamegraph_with_symbols](https://user-images.githubusercontent.com/8156163/187860690-9a685a1d-2d15-4765-aa71-5914e339149d.svg)

**Comment by amboar** [comment]
Okay, maybe valgrind's DHAT might help here if you're using an AST2600:

https://valgrind.org/docs/manual/dh-manual.html

**Comment by randomnezz** [comment]
I traced down what takes the most time in my use case with time measurements and logs added in the code. It looks that updating property on line 171 in associations.cpp takes ~85% of time. It also takes increasing amount of time with more added objects (property is set with larger vector as value). I don't think updating/appending property on dbus is possible, so the only solution that comes to mind is less frequent update of the value, i.e. not with each association change signal.

**Comment by randomnezz** [comment]
@bradbishop @amboar @geissonator @spinler @mdmillerii The issue is that adding many associations to the same interface, each of them is processed separately and with each update new value on the interface is set. This means sending (1+2+3+...+n) strings as property value. This could be optimized to send it only n strings after all associations are processed. Do you think it could be done?

**Comment by randomnezz** [comment]
Issue is fixed with https://github.com/openbmc/phosphor-objmgr/commit/5b4357da283bb924e6ce8e94f594c42b17eda39c
